const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const core=require('../lib/payment-core'),pricing=require('../lib/pricing'),display=require('./fixtures/payment-display');
const cart={checkoutId:'12345678-1234-1234-1234-123456789012',method:'razorpay',shopId:'shop1',items:[{productId:'p1',qty:2}],phone:'9876543210',deliveryAddress:'1 Main Street, Coimbatore - 641001',deliveryLat:11,deliveryLng:77};
const shop={name:'Shop',lat:11,lng:77,ownerUid:'vendor1'},product={name:'Rice',category:'grocery',shopId:'shop1',vendorBasePrice:100,price:100,stock:50,maxPerUser:5};
const sign=(s,key='test-secret')=>crypto.createHmac('sha256',key).update(s).digest('hex');
test('pricing shares exact customer formulas, slabs and categories',()=>{assert.equal(pricing.getCustomerPrice(100),110);for(const [d,fee] of [[0,25],[2,25],[2.01,35],[4,35],[4.01,50],[6,50],[6.01,60],[7,60]])assert.equal(pricing.getDeliveryPricing(d).deliveryFee,fee);assert.equal(pricing.getDeliveryPricing(7.01).serviceable,false);const q=core.quote(core.input({...cart,amount:1,total:1}),shop,{p1:product},{uid:'u1'});assert.equal(q.total,245);assert.equal(q.vendorCommissionAmount,6);assert.equal(q.vendorEarnings,194);assert.equal(q.zorraProductRevenue,26);assert.equal(q.customerUid,'u1');});
test('rejects malformed quantities, duplicated products, low totals, wrong shop, stock and medical omissions',()=>{for(const qty of [0,-1,1.5,NaN,10000])assert.throws(()=>core.input({...cart,items:[{productId:'p1',qty}]}));assert.throws(()=>core.input({...cart,items:[...cart.items,...cart.items]}));assert.throws(()=>core.quote({...cart,items:[{productId:'p1',qty:1}]},shop,{p1:product},{uid:'u'}));assert.throws(()=>core.quote(cart,shop,{p1:{...product,shopId:'wrong'}},{uid:'u'}));assert.throws(()=>core.quote(cart,shop,{p1:{...product,stock:1}},{uid:'u'}));assert.throws(()=>core.quote(cart,shop,{p1:{...product,name:'Medical tablet'}},{uid:'u'}));});
test('HMAC is exact and capture requires matching order, amount and currency',()=>{assert(core.signature('a|b',sign('a|b'),'test-secret'));for(const sig of ['',null,'zz'.repeat(32),sign('a|c')])assert.equal(core.signature('a|b',sig,'test-secret'),false);const a={razorpayOrderId:'order_1',amount:24500},p={order_id:'order_1',amount:24500,currency:'INR',status:'captured'};core.captured(p,a);for(const patch of [{amount:1},{currency:'USD'},{order_id:'wrong'},{status:'authorized'}])assert.throws(()=>core.captured({...p,...patch},a));});
test('display never calls an unverified online payment paid or asks prepaid customer for cash',()=>{assert.match(display.collectionText({payment:{method:'razorpay',status:'paid',verified:true},total:245}),/Amount to Collect: ₹0/);assert.match(display.collectionText({payment:{method:'cod'},customerTotal:245}),/₹245/);assert.equal(display.info({payment:{method:'razorpay',status:'paid',verified:false}}).label,'Payment Pending');assert.equal(display.info({paymentMethod:'online'}).paid,false);assert(!display.html({payment:{method:'razorpay',instrument:'<script>'}}).includes('<script>'));});
function harness(){
 const data=new Map([['shops/shop1',shop],['products/p1',product]]);let queue=Promise.resolve(),creates=0;const payments=new Map(),orders=new Map();
 const clone=x=>x===undefined?undefined:structuredClone(x);
 function snap(ref){return{exists:data.has(ref.path),data:()=>clone(data.get(ref.path)),id:ref.path.split('/').at(-1)};}
 function put(ref,v,merge=false){const p=clone(data.get(ref.path)||{}),values=clone(v);for(const [k,x] of Object.entries(values))if(x&&typeof x==='object'&&'increment'in x)values[k]=(p[k]||0)+x.increment;data.set(ref.path,merge?{...p,...values}:values);}
 function ref(p){return{path:p,get:async()=>snap({path:p}),update:async v=>put({path:p},v,true)};}
 const db={collection:name=>({doc:id=>ref(name+'/'+id)}),runTransaction:fn=>{const run=queue.then(async()=>{const writes=[];const tx={get:async r=>snap(r),create:(r,v)=>{assert(!data.has(r.path));writes.push(()=>put(r,v));},update:(r,v)=>writes.push(()=>put(r,v,true)),set:(r,v)=>writes.push(()=>put(r,v))};const result=await fn(tx);writes.forEach(f=>f());return result;});queue=run.catch(()=>{});return run;}};
 class RP{constructor(){this.orders={create:async payload=>{creates++;const o={...payload,id:'order_'+creates};orders.set(o.id,o);return o;},fetch:async id=>orders.get(id),fetchPayments:async id=>({items:[...payments.values()].filter(p=>p.order_id===id)})};this.payments={fetch:async id=>payments.get(id)};}}
 class HE extends Error{constructor(code,msg){super(msg);this.code=code;}}
 const exports={};const deps={'firebase-functions/v2/https':{onCall:(o,f)=>f,onRequest:(o,f)=>f,HttpsError:HE},'firebase-functions/params':{defineSecret:name=>({value:()=>name==='RAZORPAY_KEY_ID'?'rzp_test_mock':name==='RAZORPAY_WEBHOOK_SECRET'?'webhook-secret':'test-secret'}),defineBoolean:name=>({value:()=>name==='ZORRA_CHECKOUT_ENABLED'})},'firebase-admin/app':{initializeApp:()=>{}},'firebase-admin/firestore':{getFirestore:()=>db,FieldValue:{serverTimestamp:()=>({seconds:123}),increment:n=>({increment:n})}},razorpay:RP};
 const file=path.resolve(__dirname,'../index.js');vm.runInNewContext(fs.readFileSync(file,'utf8'),{require:n=>deps[n]||require(path.resolve(path.dirname(file),n)),exports,console,Date,Intl},{filename:file});
 const req=(d,uid='u1')=>({data:d,auth:{uid,token:{name:'Customer',email:'customer@example.test'}}});
 async function webhook(event,p,refund,eventId='event1'){const body={event,payload:{payment:{entity:p},...(refund?{refund:{entity:refund}}:{})}},rawBody=Buffer.from(JSON.stringify(body));let status;await exports.razorpayWebhook({method:'POST',body,rawBody,get:n=>n==='x-razorpay-signature'?sign(rawBody,'webhook-secret'):eventId},{sendStatus:n=>{status=n;}});return status;}
 return{exports,data,req,payments,orders,webhook,get creates(){return creates;}};
}
test('concurrent creates, duplicate verify and webhook produce one order; late failures cannot undo payment',async()=>{const h=harness();const results=await Promise.allSettled([h.exports.createRazorpayOrder(h.req(cart)),h.exports.createRazorpayOrder(h.req(cart))]);const r=results.find(x=>x.status==='fulfilled').value;assert.equal(h.creates,1);assert.equal([...h.data.keys()].filter(x=>x.startsWith('orders/')).length,0);const again=await h.exports.createRazorpayOrder(h.req(cart));assert.equal(again.razorpayOrderId,r.razorpayOrderId);const p={id:'pay_1',order_id:r.razorpayOrderId,amount:r.amount,currency:'INR',status:'captured',method:'upi'};h.payments.set(p.id,p);const v={zorraOrderId:r.zorraOrderId,razorpay_order_id:r.razorpayOrderId,razorpay_payment_id:p.id,razorpay_signature:sign(r.razorpayOrderId+'|'+p.id)};await assert.rejects(h.exports.verifyRazorpayPayment(h.req(v,'wrong')));await Promise.all([h.exports.verifyRazorpayPayment(h.req(v)),h.exports.verifyRazorpayPayment(h.req(v))]);assert.equal(await h.webhook('payment.captured',p),200);assert.equal(await h.webhook('payment.captured',p),200);assert.equal(await h.webhook('payment.failed',{...p,status:'failed'},null,'event2'),200);const o=h.data.get('orders/'+r.zorraOrderId);assert.equal(o.payment.status,'paid');assert.equal(o.total,245);assert.equal([...h.data.keys()].filter(x=>x.startsWith('orders/')).length,1);});
test('bad signature and authorized payment never create fulfilment order; webhook recovers missed callback',async()=>{const h=harness(),r=await h.exports.createRazorpayOrder(h.req(cart)),p={id:'pay_2',order_id:r.razorpayOrderId,amount:r.amount,currency:'INR',status:'authorized'};h.payments.set(p.id,p);const v={zorraOrderId:r.zorraOrderId,razorpay_order_id:r.razorpayOrderId,razorpay_payment_id:p.id,razorpay_signature:'0'.repeat(64)};await assert.rejects(h.exports.verifyRazorpayPayment(h.req(v)));v.razorpay_signature=sign(r.razorpayOrderId+'|'+p.id);await assert.rejects(h.exports.verifyRazorpayPayment(h.req(v)));assert(!h.data.has('orders/'+r.zorraOrderId));p.status='captured';await h.webhook('payment.captured',p);assert.equal(h.data.get('orders/'+r.zorraOrderId).status,'Confirmed');});
test('refund replay and late captured events cannot reduce refund; cancelled fulfilment is preserved',async()=>{const h=harness(),r=await h.exports.createRazorpayOrder(h.req(cart)),p={id:'pay_3',order_id:r.razorpayOrderId,amount:r.amount,currency:'INR',status:'captured'};h.payments.set(p.id,p);await h.webhook('payment.captured',p);const order=h.data.get('orders/'+r.zorraOrderId);order.status='Cancelled';p.amount_refunded=1000;await h.webhook('refund.processed',p,{id:'rf_1',payment_id:p.id,status:'processed'},'refund1');assert.equal(h.data.get('orders/'+r.zorraOrderId).refund.status,'partially_refunded');p.amount_refunded=r.amount;p.status='refunded';await h.webhook('refund.processed',p,{id:'rf_2',payment_id:p.id,status:'processed'},'refund2');p.amount_refunded=0;p.status='captured';await h.webhook('payment.captured',p,null,'late');const final=h.data.get('orders/'+r.zorraOrderId);assert.equal(final.payment.status,'refunded');assert.equal(final.refund.amount,245);assert.equal(final.status,'Cancelled');});
test('COD is server priced and idempotent; delivery settlement credits once',async()=>{const h=harness(),r=await h.exports.createCodOrder(h.req({...cart,method:'cod',total:1}));await h.exports.createCodOrder(h.req({...cart,method:'cod'}));assert.equal(h.creates,0);const o=h.data.get('orders/'+r.zorraOrderId);assert.equal(o.codCollectionTotal,245);assert.equal(o.payment.verified,false);Object.assign(o,{status:'Delivered',customerConfirmed:true,deliveryPartnerId:'rider1'});h.data.set('delivery_partners/rider1',{walletBalance:0});await assert.rejects(h.exports.finalizeZorraDelivery(h.req({orderId:r.zorraOrderId},'wrong')));await Promise.all([h.exports.finalizeZorraDelivery(h.req({orderId:r.zorraOrderId},'rider1')),h.exports.finalizeZorraDelivery(h.req({orderId:r.zorraOrderId},'rider1'))]);assert.equal(h.data.get('delivery_partners/rider1').walletBalance,25);assert.equal(h.data.get('delivery_wallet_transactions/'+r.zorraOrderId).month.length,7);});
