(function(){
 // Define this immediately so the existing checkout handler never throws
 // "ZorraCheckout is not defined" while dependencies are loading.
 window.ZorraCheckout=window.ZorraCheckout||{successMessage:'Order confirmed.',place:null};
 let functions=null;let busy=false,loader;
 function initFunctions(){
  if(functions)return functions;
  if(!window.firebase||!firebase.app||!firebase.app().functions)throw Error('Firebase Functions SDK is missing. Add firebase-functions-compat.js before payment.js.');
  functions=firebase.app().functions('asia-south1');return functions;
 }
 const call=async(name,data)=>(await initFunctions().httpsCallable(name)(data)).data;
 const storageKey=()=> 'zorra-secure-checkout:'+auth.currentUser.uid;
 function getSaved(){try{return JSON.parse(localStorage.getItem(storageKey())||'null');}catch(e){return null;}}
 function save(v){localStorage.setItem(storageKey(),JSON.stringify(v));}
 async function digest(data){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(data)));return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');}
 function load(){if(window.Razorpay)return Promise.resolve();if(loader)return loader;loader=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve();s.onerror=()=>{loader=null;s.remove();reject(Error('Secure payment could not load. Your cart is saved.'));};document.head.appendChild(s);});return loader;}
 function checkout(r,order){return new Promise((resolve,reject)=>{let finished=false;const fail=message=>{if(finished)return;finished=true;reject(Error(message));};const razorpay=new Razorpay({key:r.keyId,amount:r.amount,currency:'INR',order_id:r.razorpayOrderId,name:'ZORRA',description:'ZORRA Order Payment',prefill:{name:auth.currentUser.displayName||'',email:auth.currentUser.email||'',contact:order.phone},handler:async response=>{try{const result=await call('verifyRazorpayPayment',{...response,zorraOrderId:r.zorraOrderId});if(result.status!=='confirmed')return fail('Payment is not confirmed. Check its status before retrying.');if(!finished){finished=true;resolve(result);}}catch(e){fail('Payment confirmation is pending. If your bank debited you, do not pay again. Use Check payment status.');}},modal:{ondismiss:()=>fail('Payment window closed. Your cart is saved. Check payment status before paying again.')}});razorpay.on('payment.failed',()=>{toast('Payment attempt failed. You can try again inside secure checkout or close it and check status.','err');});razorpay.open();});}
 window.ZorraCheckout.successMessage='Order confirmed.';window.ZorraCheckout.place=async function(order){
  const method=document.getElementById('pay-online').checked?'razorpay':'cod';
  const data={method,shopId:order.shopId,items:order.items.map(i=>({productId:i.productId,qty:i.qty})).sort((a,b)=>a.productId.localeCompare(b.productId)),phone:order.phone,deliveryAddress:order.deliveryAddress,deliveryLat:order.deliveryLat,deliveryLng:order.deliveryLng,medicalIdProof:order.medicalIdProof,medicalIdFileName:order.medicalIdFileName};
  const fingerprint=await digest(data);let saved=getSaved();
  if(saved&&saved.fingerprint!==fingerprint&&!saved.completed)throw Error('A previous checkout is unresolved. Use Check payment status before changing the order or payment method.');
  if(!saved||(saved.completed&&saved.fingerprint!==fingerprint)){saved={checkoutId:crypto.randomUUID(),fingerprint,method,completed:false};save(saved);}
  const button=document.getElementById('btn-confirm-order');button.textContent=method==='razorpay'?'Opening secure payment...':'Confirming order...';
  const r=await call(method==='razorpay'?'createRazorpayOrder':'createCodOrder',{...data,checkoutId:saved.checkoutId});saved.zorraOrderId=r.zorraOrderId;save(saved);showStatusButton();
  if(method==='razorpay'&&r.status!=='confirmed'){if(r.status==='refunded')throw Error('This payment was refunded. Contact support before placing a new order.');await load();await checkout(r,order);}
  // Keep the completed key until the original checkout has cleared its cart.
  saved.completed=true;save(saved);window.ZorraCheckout.successMessage=method==='razorpay'?'Payment successful. Your order has been confirmed.':'Cash on Delivery order confirmed.';
 };
 const original=window.confirmOrder;window.confirmOrder=async function(){if(busy)return;busy=true;try{return await original.apply(this,arguments);}finally{busy=false;}};
 const render=window.renderOrderItemsList;window.renderOrderItemsList=function(o){return render(o)+ZorraPayment.html(o,'customer');};
 const renderOrders=window.renderOrdersModal;window.renderOrdersModal=function(){const result=renderOrders.apply(this,arguments);const host=document.createElement('div');host.id='zorra-pending-payments';document.getElementById('orders-body').appendChild(host);call('listMyZorraPaymentAttempts',{}).then(r=>{if(!host.isConnected)return;r.attempts.forEach(a=>{const row=document.createElement('div');row.className='order-card';const title=document.createElement('strong');title.textContent=a.shopName+' · ₹'+a.total+' · '+(a.state==='failed'?'Payment Failed':'Payment Pending');row.appendChild(title);const b=document.createElement('button');b.className='btn-confirm';b.textContent='Check payment status';b.onclick=async()=>{b.disabled=true;try{const status=await call('getZorraPaymentStatus',{zorraOrderId:a.id});toast(status.status==='confirmed'?'Payment successful. Your order has been confirmed.':'Payment status: '+status.status);if(status.status==='confirmed')openOrdersModal();}catch(e){toast(e.message,'err');}finally{b.disabled=false;}};row.appendChild(b);host.appendChild(row);});}).catch(()=>{host.textContent='Payment attempts could not be loaded. Please check your connection.';});return result;};
 function showStatusButton(){let b=document.getElementById('zorra-check-payment');if(!b){b=document.createElement('button');b.id='zorra-check-payment';b.type='button';b.className='btn-confirm';b.textContent='Check payment status';document.getElementById('btn-confirm-order').insertAdjacentElement('afterend',b);b.onclick=async()=>{const s=getSaved();if(!s?.zorraOrderId)return toast('No payment reference yet. Reopen this same checkout to recover its reference, or contact support.','err');b.disabled=true;try{const r=await call('getZorraPaymentStatus',{zorraOrderId:s.zorraOrderId});toast(r.status==='confirmed'?'Your order is confirmed. View it in My Orders.':r.status==='refunded'?'Payment refunded.':'Payment is '+r.status+'. Do not start another payment if your bank debited you.');if(r.status==='confirmed'){s.completed=true;save(s);closeDeliveryModal();openOrdersModal();}}catch(e){toast(e.message,'err');}finally{b.disabled=false;}};}b.style.display=getSaved()?'block':'none';}
 auth.onAuthStateChanged(u=>{if(u){showStatusButton();const s=getSaved();if(s&&!s.completed)toast('A checkout is pending. Open checkout and use Check payment status before placing another order.','info');}});
 const newOrder=document.createElement('button');newOrder.type='button';newOrder.className='btn-confirm';newOrder.textContent='Start a separate new order';newOrder.style.display='none';document.getElementById('btn-confirm-order').insertAdjacentElement('afterend',newOrder);
 const baseCheckout=window.checkoutCart;window.checkoutCart=function(){const r=baseCheckout.apply(this,arguments);newOrder.style.display=auth.currentUser&&getSaved()?.completed?'block':'none';return r;};
 newOrder.onclick=async()=>{const saved=getSaved();if(!saved?.completed)return;if(!confirm('Your earlier order is already confirmed. Start a separate order that will require a new payment or COD collection?'))return;localStorage.removeItem(storageKey());newOrder.style.display='none';toast('New checkout started. Review the cart and payment method before confirming.');};
})();
