'use strict';
const {onCall,onRequest,HttpsError}=require('firebase-functions/v2/https');
const {defineSecret,defineBoolean}=require('firebase-functions/params');
const {initializeApp}=require('firebase-admin/app');
const {getFirestore,FieldValue}=require('firebase-admin/firestore');
const Razorpay=require('razorpay');
const core=require('./lib/payment-core');
initializeApp();const db=getFirestore();
const keyId=defineSecret('RAZORPAY_KEY_ID'),keySecret=defineSecret('RAZORPAY_KEY_SECRET'),webhookSecret=defineSecret('RAZORPAY_WEBHOOK_SECRET');
const enabled=defineBoolean('ZORRA_CHECKOUT_ENABLED',{default:false});
const live=defineBoolean('RAZORPAY_ALLOW_LIVE',{default:false});
const opts={region:'asia-south1',timeoutSeconds:60,maxInstances:10};
function gateway(){core.assert(live.value()||keyId.value().startsWith('rzp_test_'),'Only Test Mode is enabled');return new Razorpay({key_id:keyId.value(),key_secret:keySecret.value()});}
function user(req){if(!req.auth)throw new HttpsError('unauthenticated','Please sign in to checkout.');return{uid:req.auth.uid,name:req.auth.token.name||'',email:req.auth.token.email||''};}
function guarded(fn){return async req=>{const u=user(req);if(!enabled.value())throw new HttpsError('failed-precondition','Secure checkout setup is not enabled yet.');try{return await fn(req,u);}catch(e){if(e instanceof HttpsError)throw e;throw new HttpsError('failed-precondition',e instanceof Error?e.message:'Payment service unavailable. Check order history before retrying.');}};}
const attempts=db.collection('payment_attempts');
function safe(a,id){return{zorraOrderId:id,razorpayOrderId:a.razorpayOrderId||'',amount:a.amount,currency:'INR',keyId:a.method==='razorpay'?keyId.value():null,status:a.state};}
async function create(req,u){const cart=core.input(req.data),id=core.hash([u.uid,cart.checkoutId]).slice(0,40),ref=attempts.doc(id),fingerprint=core.hash(cart);let created=false;
 await db.runTransaction(async tx=>{created=false;const existing=await tx.get(ref);if(existing.exists){core.assert(existing.data().fingerprint===fingerprint,'This checkout already exists with different details. Resolve it before placing another order.');return;}
 const shopSnap=await tx.get(db.collection('shops').doc(cart.shopId));const products={};for(const i of cart.items){const snap=await tx.get(db.collection('products').doc(i.productId));products[i.productId]=snap.exists?snap.data():null;}
 // Limit abuse without trusting browser throttling. Existing attempts remain resumable.
 const rateRef=db.collection('payment_rate_limits').doc(u.uid),rate=await tx.get(rateRef),now=Date.now(),r=rate.data()||{};core.assert(now-(r.startedAt||0)>=3600000||(r.count||0)<20,'Too many checkout attempts. Please try later.');
 const order=core.quote(cart,shopSnap.exists?shopSnap.data():null,products,u),amount=Math.round(order.customerTotal*100);
 const a={customerUid:u.uid,fingerprint,method:cart.method,amount,order,state:cart.method==='cod'?'confirmed':'creating',createdAt:FieldValue.serverTimestamp()};tx.create(ref,a);tx.set(rateRef,{startedAt:now-(r.startedAt||0)>=3600000?now:r.startedAt,count:now-(r.startedAt||0)>=3600000?1:(r.count||0)+1});
 if(cart.method==='cod')tx.create(db.collection('orders').doc(id),{...order,status:'Confirmed',orderStatus:'confirmed',paymentStatus:'Pending',payment:{method:'cod',gateway:null,status:'pending',verified:false,paidAt:null}});created=true;});
 let a=(await ref.get()).data();if(cart.method==='cod')return safe(a,id);
 if(!created){if(a.razorpayOrderId)return safe(a,id);throw new HttpsError('aborted','Payment order is being created or awaiting reconciliation. Do not start a second payment.');}
 // Never automatically repeat an ambiguous provider create call: its first response may have been lost.
 let rp;try{rp=await gateway().orders.create({amount:a.amount,currency:'INR',receipt:id,notes:{zorraOrderId:id}});}catch(e){await ref.update({state:'creation_unknown'});throw new HttpsError('unavailable','Unable to open payment. The attempt is saved; contact support if it remains pending.');}
 core.assert(rp.amount===a.amount&&rp.currency==='INR','Gateway order mismatch');
 await db.runTransaction(async tx=>{const current=(await tx.get(ref)).data();core.assert(!current.razorpayOrderId||current.razorpayOrderId===rp.id,'Gateway order conflict');tx.update(ref,{razorpayOrderId:rp.id,...(['creating','creation_unknown'].includes(current.state)?{state:'pending'}:{})});});
 return safe((await ref.get()).data(),id);
}
exports.createRazorpayOrder=onCall({...opts,secrets:[keyId,keySecret]},guarded(async(req,u)=>{core.assert(req.data?.method==='razorpay','Select online payment');return create(req,u);}));
exports.createCodOrder=onCall({...opts},guarded(async(req,u)=>{core.assert(req.data?.method==='cod','Select Cash on Delivery');return create(req,u);}));
async function applyPayment(id,payment,eventId,refund){const ref=attempts.doc(id),orderRef=db.collection('orders').doc(id),eventRef=eventId?db.collection('payment_webhook_events').doc(core.hash(eventId)):null;
 return db.runTransaction(async tx=>{const snap=await tx.get(ref),orderSnap=await tx.get(orderRef),event=eventRef?await tx.get(eventRef):null;if(event?.exists)return{status:'duplicate'};core.assert(snap.exists,'Unknown payment attempt');const a=snap.data();core.captured(payment,a);core.assert(a.method==='razorpay','Wrong payment method');const prior=orderSnap.data();core.assert(!prior?.payment?.razorpayPaymentId||prior.payment.razorpayPaymentId===payment.id,'Different payment already recorded');
 const refunded=Math.max(Number(prior?.refund?.amount||0)*100,Number(payment.amount_refunded)||0);core.assert(refunded<=a.amount,'Refund amount mismatch');const full=refunded>=a.amount;
 const paid={method:'razorpay',gateway:'razorpay',status:full?'refunded':'paid',verified:true,razorpayOrderId:a.razorpayOrderId,razorpayPaymentId:payment.id,instrument:payment.method||'',paidAt:prior?.payment?.paidAt||FieldValue.serverTimestamp()};
 const update={payment:paid,paymentStatus:full?'Refunded':'Paid',updatedAt:new Date().toISOString()};
 if(refunded||refund){update.refund={...(prior?.refund||{}),status:full?'processed':refunded?'partially_refunded':refund.status,amount:refunded/100,refundId:refund?.id||prior?.refund?.refundId||'',processedAt:refunded?FieldValue.serverTimestamp():null};}
 if(orderSnap.exists)tx.update(orderRef,update);else tx.create(orderRef,{...a.order,...update,status:full?'Cancelled':'Confirmed',orderStatus:full?'cancelled':'confirmed'});
 tx.update(ref,{state:full?'refunded':'confirmed',razorpayPaymentId:payment.id});if(eventRef)tx.create(eventRef,{eventId,processedAt:FieldValue.serverTimestamp(),zorraOrderId:id});return{zorraOrderId:id,status:full?'refunded':'confirmed'};});
}
exports.verifyRazorpayPayment=onCall({...opts,secrets:[keyId,keySecret]},guarded(async(req,u)=>{const d=req.data||{};core.assert(/^[a-f0-9]{40}$/.test(d.zorraOrderId),'Invalid order reference');const ref=attempts.doc(d.zorraOrderId),s=await ref.get(),a=s.data();core.assert(s.exists&&a.customerUid===u.uid,'Order is unavailable');core.assert(d.razorpay_order_id===a.razorpayOrderId,'Payment order mismatch');core.assert(/^pay_[A-Za-z0-9]+$/.test(d.razorpay_payment_id),'Invalid payment reference');if(!core.signature(a.razorpayOrderId+'|'+d.razorpay_payment_id,d.razorpay_signature,keySecret.value())){await db.runTransaction(async tx=>{const latest=(await tx.get(ref)).data();if(!['confirmed','refunded'].includes(latest.state))tx.update(ref,{state:'failed',verificationFailedAt:FieldValue.serverTimestamp()});});throw new HttpsError('permission-denied','Payment verification failed. Check payment status before trying again.');}const p=await gateway().payments.fetch(d.razorpay_payment_id);return applyPayment(d.zorraOrderId,p);}));
exports.getZorraPaymentStatus=onCall({...opts,secrets:[keyId,keySecret]},guarded(async(req,u)=>{const id=req.data?.zorraOrderId;core.assert(/^[a-f0-9]{40}$/.test(id),'Invalid order reference');const a=(await attempts.doc(id).get()).data();core.assert(a&&a.customerUid===u.uid,'Order is unavailable');if(a.method==='razorpay'&&a.razorpayOrderId&&!['confirmed','refunded'].includes(a.state)){const list=await gateway().orders.fetchPayments(a.razorpayOrderId);const p=list.items.find(p=>p.status==='captured'||p.status==='refunded');if(p)return applyPayment(id,p);}return safe(a,id);}));
exports.listZorraPaymentAttempts=onCall(opts,guarded(async(req,u)=>{
 core.assert(req.auth.token.email==='nexcartofficial@gmail.com'&&req.auth.token.email_verified===true,'Verified administrator required');
 const before=req.data?.before;let q=attempts.orderBy('createdAt','desc').limit(100);if(before){const s=await attempts.doc(String(before)).get();core.assert(s.exists,'Invalid cursor');q=q.startAfter(s);}
 const snap=await q.get();return{attempts:snap.docs.map(s=>{const a=s.data();return{id:s.id,customerUid:a.customerUid,customerName:a.order.customerName,shopName:a.order.shopName,total:a.amount/100,state:a.state,razorpayOrderId:a.razorpayOrderId||'',razorpayPaymentId:a.razorpayPaymentId||''};}),next:snap.size===100?snap.docs.at(-1).id:null};
}));
exports.listMyZorraPaymentAttempts=onCall(opts,guarded(async(req,u)=>{
 const snap=await attempts.where('customerUid','==',u.uid).limit(100).get();return{attempts:snap.docs.map(s=>{const a=s.data();return{id:s.id,shopName:a.order.shopName,total:a.amount/100,state:a.state,method:a.method};}).filter(a=>!['confirmed','refunded'].includes(a.state))};
}));
exports.razorpayWebhook=onRequest({...opts,secrets:[keyId,keySecret,webhookSecret]},async(req,res)=>{if(req.method!=='POST')return res.sendStatus(405);if(!core.signature(req.rawBody,req.get('x-razorpay-signature'),webhookSecret.value()))return res.sendStatus(401);try{const body=req.body,eventId=req.get('x-razorpay-event-id')||core.hash(req.rawBody.toString('utf8'));if(!['payment.captured','order.paid','payment.failed','refund.created','refund.processed','refund.failed'].includes(body.event))return res.sendStatus(200);
 const refund=body.payload?.refund?.entity;let payment=body.payload?.payment?.entity;const api=gateway();if(refund)payment=await api.payments.fetch(refund.payment_id);if(!payment&&body.payload?.order?.entity){const ps=await api.orders.fetchPayments(body.payload.order.entity.id);payment=ps.items.find(p=>['captured','refunded'].includes(p.status));}core.assert(payment?.order_id,'Missing payment');const rp=await api.orders.fetch(payment.order_id),id=rp.notes?.zorraOrderId;if(!/^[a-f0-9]{40}$/.test(id||''))return res.sendStatus(200);
 const ref=attempts.doc(id);await db.runTransaction(async tx=>{const s=await tx.get(ref);core.assert(s.exists,'Missing attempt');const a=s.data();core.assert(a.amount===rp.amount&&rp.currency==='INR'&&rp.receipt===id,'Order mismatch');core.assert(!a.razorpayOrderId||a.razorpayOrderId===rp.id,'Order conflict');if(!a.razorpayOrderId)tx.update(ref,{razorpayOrderId:rp.id});});
 if(body.event==='payment.failed'){await db.runTransaction(async tx=>{const er=db.collection('payment_webhook_events').doc(core.hash(eventId)),e=await tx.get(er),s=await tx.get(ref);if(e.exists)return;if(!['confirmed','refunded'].includes(s.data().state))tx.update(ref,{state:'failed'});tx.create(er,{eventId,processedAt:FieldValue.serverTimestamp()});});}else{payment=await api.payments.fetch(payment.id);await applyPayment(id,payment,eventId,refund);}return res.sendStatus(200);
 }catch(e){console.error('Razorpay webhook processing failed; provider should retry.');return res.sendStatus(500);}});
// Preserve the supplied delivery page's final full-delivery-fee settlement policy.
exports.finalizeZorraDelivery=onCall(opts,guarded(async(req,u)=>{const id=req.data?.orderId;core.assert(typeof id==='string'&&/^[^/]{1,150}$/.test(id),'Invalid order');return db.runTransaction(async tx=>{const or=db.collection('orders').doc(id),lr=db.collection('delivery_wallet_transactions').doc(id),os=await tx.get(or),ls=await tx.get(lr);core.assert(os.exists,'Order not found');const o=os.data();core.assert(o.deliveryPartnerId===u.uid&&o.status==='Delivered'&&o.customerConfirmed===true,'Customer confirmation and assigned partner are required');const pr=db.collection('delivery_partners').doc(u.uid),ps=await tx.get(pr);core.assert(ps.exists,'Partner not found');core.assert(!ls.exists||ls.data().partnerId===u.uid,'Ledger belongs to another partner');if(ls.exists)return{settled:true};const earn=require('./lib/delivery-fee')(o);core.assert(Number.isFinite(earn)&&earn>=0,'Missing delivery fee; admin review required');const now=new Date().toISOString(),month=new Date(new Date(o.deliveredAt||o.customerConfirmedAt||now).getTime()+19800000).toISOString().slice(0,7);tx.update(pr,{walletBalance:FieldValue.increment(earn),totalEarnings:FieldValue.increment(earn),grossDeliveryEarnings:FieldValue.increment(earn),activeOrderId:null,updatedAt:now,completedOrders:FieldValue.increment(1)});tx.update(or,{deliveryPartnerPayout:earn,partnerEarnings:earn,deliveryGrossEarning:earn,deliveryAdminCommission:0,zorraDeliveryMargin:0,deliverySalaryMonth:month,updatedAt:now});tx.create(lr,{orderId:id,partnerId:u.uid,grossAmount:earn,partnerNetAmount:earn,adminCommission:0,deliveryPartnerPayout:earn,zorraDeliveryMargin:0,type:'delivery_credit',month,createdAt:now,updatedAt:now});return{settled:true};});}));
