// Extracted verbatim from supplied customer pricing-v3. Shared by browser and server.
(function(root){
  var roundMoney=function(v){return Math.round((Number(v)||0)*100)/100;};
  function categoryRate(category){var c=String(category||'').toLowerCase();if(/grocery|essential|dairy|household|provision/.test(c))return .03;if(/fruit|vegetable|produce/.test(c))return .04;if(/bakery|snack/.test(c))return .06;if(/restaurant|food|meal|cafe|hotel/.test(c))return .10;return .05;}
  function customerPrice(vendorPrice){return roundMoney((Number(vendorPrice)||0)*1.10);}
  function getDeliveryPricing(distanceKm){var d=Number(distanceKm),result={distanceKm:d,deliveryFee:0,partnerPayout:0,zorraDeliveryMargin:0,serviceable:false};if(!isFinite(d)||d<0)return result;if(d<=2)Object.assign(result,{deliveryFee:25,partnerPayout:22,zorraDeliveryMargin:3,serviceable:true});else if(d<=4)Object.assign(result,{deliveryFee:35,partnerPayout:30,zorraDeliveryMargin:5,serviceable:true});else if(d<=6)Object.assign(result,{deliveryFee:50,partnerPayout:42,zorraDeliveryMargin:8,serviceable:true});else if(d<=7)Object.assign(result,{deliveryFee:60,partnerPayout:50,zorraDeliveryMargin:10,serviceable:true});return result;}
  function linePricing(item){var qty=Math.max(0,Number(item.qty)||0),base=Number(item.vendorBasePrice!=null?item.vendorBasePrice:item.baseVendorPrice!=null?item.baseVendorPrice:item._vendorBasePrice!=null?item._vendorBasePrice:item.price/1.10)||0,rate=categoryRate(item.category),vendorValue=roundMoney(base*qty),customerValue=roundMoney(customerPrice(base)*qty),markup=roundMoney(customerValue-vendorValue),commission=roundMoney(vendorValue*rate);return{vendorBasePrice:base,customerUnitPrice:customerPrice(base),vendorValue:vendorValue,customerValue:customerValue,customerMarkup:markup,vendorCommissionPercentage:roundMoney(rate*100),vendorCommissionAmount:commission,vendorEarnings:roundMoney(vendorValue-commission),zorraProductRevenue:roundMoney(markup+commission)};}
  function orderPricing(items){return(items||[]).reduce(function(a,item){var p=linePricing(item);a.vendorBasePrice=roundMoney(a.vendorBasePrice+p.vendorValue);a.customerProductPrice=roundMoney(a.customerProductPrice+p.customerValue);a.customerMarkup=roundMoney(a.customerMarkup+p.customerMarkup);a.vendorCommissionAmount=roundMoney(a.vendorCommissionAmount+p.vendorCommissionAmount);a.vendorEarnings=roundMoney(a.vendorEarnings+p.vendorEarnings);a.zorraProductRevenue=roundMoney(a.zorraProductRevenue+p.zorraProductRevenue);a.rates[p.vendorCommissionPercentage]=true;return a;},{vendorBasePrice:0,customerProductPrice:0,customerMarkup:0,vendorCommissionAmount:0,vendorEarnings:0,zorraProductRevenue:0,rates:{}});}

const api={roundMoney,getCategoryCommissionRate:categoryRate,getCustomerPrice:customerPrice,getDeliveryPricing,getLinePricing:linePricing,getOrderPricing:orderPricing}; if(typeof module!=="undefined"&&module.exports)module.exports=api;else root.ZorraPricingCore=api;
})(typeof globalThis!=="undefined"?globalThis:this);
